### ISSUE TITLE
"Tue Oct 16 20:58:56 UTC 2018" date type is invalid to moment js

### ISSUE THREAD

**Issue by prokawsar** [prokawsar/react-github#10]
Moment.js can't convert to human readable from this date format "Tue Oct 16 20:58:56 UTC 2018"
File location:
        branch: withJobs
        path: src/Components/Jobs/JobsPanel.js
        line no: 30

**Comment by zarela** [comment]
I can help with this

**Comment by zarela** [comment]
@prokawsar Would you prefer that reads for example: `Mon Sept 7 2018` or to read `40 days ago`?

**Comment by prokawsar** [comment]
Yeah
