### ISSUE TITLE
Make "Copy to clipboard" like github has

### ISSUE THREAD

**Issue by prokawsar** [prokawsar/react-github#2]
Need to work the left file icon (You can change appropriate icon) working as link copied to clipboard.

**Comment by c0de-fox** [comment]
I'll attempt to take a crack at this if you don't mind. I experimented with having a copy to clipboard function in the past, but that required a flash file that held the clipboard. Times are changing, and I'd expect the major browsers to have a JS API for copy to clipboard

**Comment by prokawsar** [comment]
It's working now with some other features. Thanks for interest
