### ISSUE TITLE
Shows a toast if username not found

### ISSUE THREAD

**Issue by prokawsar** [prokawsar/react-github#6]
Now, it's nothing happen when an invalid username is passed. It should return a toast if username not found.

**Comment by GianOrtiz** [comment]
Working on it.

**Comment by prokawsar** [comment]
@GianOrtiz So much appreciating

**Comment by prokawsar** [comment]
Working well. but throwing an error in the console, can you explain why?

**Comment by GianOrtiz** [comment]
The only error shown here is in Avatar.js, which i haven't altered. I fixed the problem adding prop alt="" to img in Avatar.js. It's the same error?
